config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: :create
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def average
    return self.reviews.map { |r| r.rating }.sum / self.reviews.count if self.reviews.count > 0
    0
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  validates :content, length: { minimum: 20 }
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_restaurants, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = policy_scope(Restaurant).order(created_at: :desc)
    @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)
    @restaurants = policy_scope(Restaurant).order(created_at: :desc)
    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: {content: render_to_string(partial: "/restaurants/map_box", locals: { restaurant: restaurant }) }
      }
    end
  end

  def show
    authorize @restaurant
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurants_params)
    @restaurant.user = current_user
    authorize @restaurant
    if @restaurant.save == true
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    authorize @restaurant
  end

  def update
    authorize @restaurant
    @restaurant.update(restaurants_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
    flash[:notice] = "Your restaurant has been removed"
    authorize @restaurant
  end

  private

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurants_params
    params.require(:restaurant).permit(:name, :photo1, :photo2, :photo3, :category, :address, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.user = current_user
    authorize @review
    if @review.save
      respond_to do |format|
        format.html { redirect_to restaurant_path(@restaurant) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'restaurants/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.1.0/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/restaurants/_infowindow.html.erb
<img src="<%= restaurant.photo1 %>" alt="">
<h2> <%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/_map_box.html.erb
<img src="<%= restaurant.photo1 %>" alt="">
<h2> <%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/edit.html.erb
<div class="form-container">
  <h2>Edit Restaurant</h2>
  <%= simple_form_for @restaurant do |f| %>
  <%= f.error_notification %>

  <%= f.input :name, label: 'Name', required: true, value: @restaurant.name %>
  <%= f.input :photo1, label: 'Photo 1', required: true, value: @restaurant.photo1 %>
  <%= f.input :photo2, label: 'Photo 2', required: true, value: @restaurant.photo2 %>
  <%= f.input :photo3, label: 'Photo 3', required: true, value: @restaurant.photo3 %>
  <%= f.input :address, label: 'Address', required: true, value: @restaurant.address %>
  <%= f.input :description, label: 'Description', required: true, value: @restaurant.description %>
  <%= f.input :category, label: 'Category', required: true, :collection => ["Italian", "Argentine", "French", "Japanesse", "Usa","Spanish"]%>

  <%= f.button :submit, "UPDATE", class: 'btn btn-primary' %>

  <% end %>
  <br>
  <%= link_to 'Go Back', restaurant_path(@restaurant) %>
</div>
<br>

app/views/restaurants/index.html.erb
<div class="restaurant-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80)">
  <div class="container">
    <h2>RESTAURANTS</h2>
  </div>
</div>
<div class="restaurant-wrapper">
  <div class="restaurant-container">
    <% @restaurants.each do |restaurant|  %>
    <%= render 'shared/cards', restaurant: restaurant%>
    <%end  %>
  </div>
  <div
  id="map"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/restaurants/new.html.erb
<div class="form-container">
  <h2>Add Restaurant</h2>
  <%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :photo1 %>
  <%= f.input :photo2 %>
  <%= f.input :photo3 %>
  <%= f.input :address %>
  <%= f.input :category, :collection => ["Italian", "Argentine", "French", "Japanesse", "Usa", "Spanish"] %>
  <%= f.input :description %>
  <%= f.submit "create restaurant", class: "btn btn-primary" %>
  <%end%>
  <br>
  <%= link_to 'Go Back', root_path %>
</div>
<br>

app/views/restaurants/show.html.erb
<%= render 'shared/carousel', restaurant: @restaurant %>
<div class="show-wrapper">
  <div class="show-container">
    <div class="show-titles">
      <div class="show-name">
        <h2><%= @restaurant.name %></h2>
      </div>
      <div class="show-rating">
        <% @restaurant.average.times do %>
        <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @restaurant.average).times do %>
        <i class="far fa-star"></i>
        <% end %>
      </div>
    </div>
    <div class="show-description">
      <h3><%= @restaurant.address %></h3>
      <h4><%= @restaurant.category %></h4>
      <p><%= @restaurant.description %></p>
    </div>
  </div>
  <div class="show-img">
    <!-- how to put statics maps images with mapbox -->
    <img src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/pin-l(<%= @restaurant.longitude %>,<%= @restaurant.latitude %>)/<%= @restaurant.longitude %>,<%= @restaurant.latitude %>,12,0.00,0.00/200x200@2x?access_token=<%= ENV['MAPBOX_API_KEY'] %>' alt='Restaurant location'  >
  </div>
</div>
<div class="count-review">
  <h1>Reviews</h1>
  <h3> <% @restaurant.average.times do %>
    <i class="fas fa-star"></i>
    <% end %>
    <% (5 - @restaurant.average).times do %>
    <i class="far fa-star"></i>
    <% end %>(<%=@restaurant.reviews.size%>)</h3>
    <p><button id="myReviewButton" onClick="myReviewFunction();" ><i class="fas fa-edit"></i> Write a review</button></p>
    <% if user_signed_in? %>
    <div style= "display:none;" id="reviewForm">
      <%= render 'reviews/form', restaurant: @restaurant, review: @review %>
      <% else %>
      <p>You must be log in to create a review</p>
      <%end  %>
    </div>
    <h2>Reviews(<span id="review-count"><%=@restaurant.reviews.size%></span>)</h2>
  </div>
  <div id="reviews">
    <% if @restaurant.reviews.blank? %>
    Be the first to leave a review for <%= @restaurant.name %>
    <% else %>
    <% @restaurant.reviews.reverse_each do |review| %>
    <%= render 'reviews/show', review: review %>
    <% end %>
    <% end %>
  </div>
  <div class="show-links">
    <%= render 'shared/links', restaurant: @restaurant %>
  </div>


  <script>
    function myReviewFunction() {
     var x = document.getElementById("reviewForm");
     x.style.display = "block";
   }
 </script>

app/views/reviews/_form.html.erb
<div class="container">
  <%= simple_form_for([ restaurant, review ], remote: true) do |form| %>
  <%= form.input :content , label: "Review:"%>
  <%= form.input :rating, required: true, :collection => ["1", "2", "3", "4", "5"] %>
  <%= form.button :submit,  class: 'button-review' %>
  <% end %>
</div>

app/views/reviews/_show.html.erb
<div class="review-wrapper">
 <div class="review-container">
  <div class="review-title">
    <img src="https://images.unsplash.com/photo-1537815749002-de6a533c64db?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1090&q=80" alt="avatar photos">
    <h3><%= review.user.email %></h3>
  </div>
  <div class="review-time">
    <p><%= review.created_at.in_time_zone("Buenos Aires").strftime('%d/%m/%y - %H:%M')  %></p>
  </div>
 </div>
  <div class="review-content">
    <% review.rating.times do %>
    <i class="fas fa-star"></i>
    <% end %>
    <h2><%= review.content %></h2>
  </div>
</div>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('afterbegin', reviewHTML);
  const reviewCount = document.getElementById('review-count');
  const newCount = parseInt(reviewCount.innerText) + 1
  reviewCount.innerText = newCount
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>



// create the html for the review

app/views/shared/_cards.html.erb
<div class="cards-container">
  <%= link_to restaurant_path(restaurant) do %>
  <div class="cards-img">
    <img src="<%= restaurant.photo1 %>" alt="restaurant photos">
  </div>
  <div class="cards-content">
    <div class="cards-name">
      <h2><%= restaurant.name %></h2>
    </div>
    <div class="cards-rating">
     <% restaurant.average.times do %>
     <i class="fas fa-star"></i>
     <% end %>
     <% (5 - restaurant.average).times do %>
     <i class="far fa-star"></i>
     <% end %>
   </div>
 </div>
 <div class="cards-middle">
  <h3><%= restaurant.address %></h3>
  <h4><%= restaurant.category %></h4>
</div>
<%end%>
</div>

app/views/shared/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="<%= @restaurant.photo1 %>/800x400?auto=yes&bg=777&fg=555&text=First slide" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="<%= @restaurant.photo2 %>/800x400?auto=yes&bg=666&fg=444&text=Second slide" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="<%= @restaurant.photo3 %>/800x400?auto=yes&bg=555&fg=333&text=Third slide" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_links.html.erb
<div class="container">
  <% if policy(@restaurant).edit?  %>
  <h2><%= link_to 'Edit' , edit_restaurant_path, class: "button-edit" %></h2>
  <%else  %>
  <%end  %>
  <% if policy(@restaurant).destroy?  %>
  <h3><button id="sweet-alert-demo" class="button-delete">Delete <%= @restaurant.name %></button></h3>
  <%= link_to "", restaurant_path(@restaurant), method: :delete, id: "delete-link", class: "hidden" %>
  <%else%>
  <% end %>
  <h4><%= link_to 'Go Back', root_path, class: "go-back"%></h4>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <i class="fab fa-fort-awesome"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
         <li class="nav-item">
        <% if policy(Restaurant).create? %>
        <%= link_to new_restaurant_path, class: "nav-link" do %>
          <i class="fas fa-plus"></i> Restaurant
        <%end %>
        <% end %>
      </li>
      </li>
      <li class="nav-item">
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link"  do %>
            <i class="fas fa-sign-out-alt"> </i> Log Out
        <%end %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>